"""Initial_migration

Revision ID: 62ed51e51659
Revises: 
Create Date: 2026-07-26 17:17:41.557336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ed51e51659'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.Enum('CSE', 'MECHANICAL', 'AEROSPACE', 'DATA_SCIENCE', 'AI_DS', 'CIVIL', 'ECE', name='department'), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=False),
    sa.Column('feature_means', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('idx_model_versions_is_active', 'model_versions', ['is_active'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=10), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('department', sa.Enum('CSE', 'MECHANICAL', 'AEROSPACE', 'DATA_SCIENCE', 'AI_DS', 'CIVIL', 'ECE', name='department'), nullable=False),
    sa.Column('section', sa.Enum('A', 'B', 'C', name='section'), nullable=False),
    sa.Column('advisor_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_department', 'students', ['department'], unique=False)
    op.create_index('idx_student_section', 'students', ['section'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('INTERNAL', 'EXTERNAL', 'ASSIGNMENT', 'PROJECT', name='assessmenttype'), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendance_student_course', 'attendance_records', ['student_id', 'course_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='idx_unique_enrollment')
    )
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('HIGH', 'MODERATE', 'STABLE', 'SAFE', name='risklevel'), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_history_recorded_at', 'risk_history', ['recorded_at'], unique=False)
    op.create_index('idx_risk_history_student_id', 'risk_history', ['student_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('HIGH', 'MODERATE', 'STABLE', 'SAFE', name='risklevel'), nullable=False),
    sa.Column('risk_trend', sa.Enum('UP', 'DOWN', 'STABLE', name='risktrend'), nullable=False),
    sa.Column('risk_value', sa.String(length=50), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_risk_scores_risk_level', 'risk_scores', ['risk_level'], unique=False)
    op.create_index('idx_risk_scores_student_id', 'risk_scores', ['student_id'], unique=False)
    op.create_table('student_coding_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('hackerrank_score', sa.Float(), nullable=True),
    sa.Column('hackerrank_solved', sa.Integer(), nullable=True),
    sa.Column('leetcode_rating', sa.Float(), nullable=True),
    sa.Column('leetcode_solved', sa.Integer(), nullable=True),
    sa.Column('codechef_rating', sa.Float(), nullable=True),
    sa.Column('codeforces_rating', sa.Float(), nullable=True),
    sa.Column('interviewbit_score', sa.Float(), nullable=True),
    sa.Column('spoj_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('attendance_rate', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('academic_performance_index', sa.Float(), nullable=False),
    sa.Column('login_gap_days', sa.Integer(), nullable=False),
    sa.Column('failure_ratio', sa.Float(), nullable=False),
    sa.Column('financial_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('commute_risk_score', sa.Integer(), nullable=False),
    sa.Column('semester_performance_trend', sa.Float(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_student_metrics_student_id', 'student_metrics', ['student_id'], unique=False)
    op.create_table('student_raw_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('assignment_name', sa.String(length=300), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_assignments_student', 'student_raw_assignments', ['student_id'], unique=False)
    op.create_table('student_raw_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_attendance_date', 'student_raw_attendance', ['date'], unique=False)
    op.create_index('idx_raw_attendance_student', 'student_raw_attendance', ['student_id'], unique=False)
    op.create_table('student_raw_marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('exam_type', sa.String(length=100), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_marks_student', 'student_raw_marks', ['student_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'ADMIN', 'DEAN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('faculty_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('pre_intervention_risk', sa.Float(), nullable=True),
    sa.Column('post_intervention_risk', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_faculty_id'), 'interventions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_index(op.f('ix_interventions_student_id'), 'interventions', ['student_id'], unique=False)
    op.create_table('student_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'PENDING', 'OVERDUE', 'GRADED', name='submissionstatus'), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assessment_id', name='idx_unique_student_assessment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_assessments')
    op.drop_index(op.f('ix_interventions_student_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_faculty_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_raw_marks_student', table_name='student_raw_marks')
    op.drop_table('student_raw_marks')
    op.drop_index('idx_raw_attendance_student', table_name='student_raw_attendance')
    op.drop_index('idx_raw_attendance_date', table_name='student_raw_attendance')
    op.drop_table('student_raw_attendance')
    op.drop_index('idx_raw_assignments_student', table_name='student_raw_assignments')
    op.drop_table('student_raw_assignments')
    op.drop_index('idx_student_metrics_student_id', table_name='student_metrics')
    op.drop_table('student_metrics')
    op.drop_table('student_coding_profiles')
    op.drop_index('idx_risk_scores_student_id', table_name='risk_scores')
    op.drop_index('idx_risk_scores_risk_level', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('idx_risk_history_student_id', table_name='risk_history')
    op.drop_index('idx_risk_history_recorded_at', table_name='risk_history')
    op.drop_table('risk_history')
    op.drop_table('enrollments')
    op.drop_index('idx_attendance_student_course', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('assessments')
    op.drop_index('idx_student_section', table_name='students')
    op.drop_index('idx_student_department', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_model_versions_is_active', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('courses')
    # ### end Alembic commands ###
