"""
initialize_student_relationships.py
────────────────────────────────────
Idempotent initialization script that repairs data-linking gaps for any student
that is enrolled in courses but missing:

  1. StudentAssessment linking rows for their enrolled course assessments.
  2. StudentMetric row (required by the ML risk pipeline).
  3. RiskScore row (generated by running the existing ML pipeline).

SAFE TO RUN MULTIPLE TIMES — checks for existing records before inserting.

Usage (from backend/ directory):
    python -m app.database.initialize_student_relationships
    python -m app.database.initialize_student_relationships --student-id STU123
"""

import sys
import logging
from datetime import datetime, timezone

from sqlalchemy.orm import Session
from sqlalchemy import func

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)


def repair_student_assessment_links(db: Session, student_id: str) -> dict:
    """
    Create missing StudentAssessment linking rows for all assessments in
    courses the student is enrolled in.

    Logic:
        enrolled_courses = Enrollment.course_id WHERE student_id = student_id
        for each Assessment WHERE course_id in enrolled_courses:
            if no StudentAssessment(student_id, assessment_id) exists:
                INSERT with status=PENDING, obtained_marks=NULL
    """
    from app.models.academic import Enrollment, Assessment
    from app.models.records import StudentAssessment
    from app.models.enums import SubmissionStatus

    enrolled_course_ids = [
        e.course_id
        for e in db.query(Enrollment).filter(Enrollment.student_id == student_id).all()
    ]

    if not enrolled_course_ids:
        log.warning(f"[{student_id}] No enrollments found — skipping assessment linking.")
        return {"created": 0, "skipped": 0}

    assessments = (
        db.query(Assessment)
        .filter(Assessment.course_id.in_(enrolled_course_ids))
        .all()
    )

    existing_assessment_ids = {
        sa.assessment_id
        for sa in db.query(StudentAssessment)
        .filter(StudentAssessment.student_id == student_id)
        .all()
    }

    created = 0
    skipped = 0

    for assessment in assessments:
        if assessment.id in existing_assessment_ids:
            skipped += 1
            continue

        sa = StudentAssessment(
            student_id=student_id,
            assessment_id=assessment.id,
            status=SubmissionStatus.PENDING,
            obtained_marks=None,
            submission_date=None,
        )
        db.add(sa)
        created += 1
        log.info(
            f"[{student_id}] Linked: assessment_id={assessment.id} "
            f"({assessment.title}, {assessment.course_id}) -> PENDING"
        )

    if created > 0:
        db.flush()

    log.info(f"[{student_id}] Assessment links: {created} created, {skipped} already existed.")
    return {"created": created, "skipped": skipped}


def ensure_student_metric(db: Session, student_id: str) -> dict:
    """
    If no StudentMetric row exists for student_id, create one with
    attendance_rate computed from real attendance_records.
    Other metric fields use safe cohort defaults until the ML pipeline
    runs a full feature-engineering pass.
    """
    from app.models.student import StudentMetric
    from app.models.records import AttendanceRecord
    from app.models.enums import AttendanceStatus

    existing = db.query(StudentMetric).filter(StudentMetric.student_id == student_id).first()
    if existing:
        log.info(
            f"[{student_id}] StudentMetric already exists "
            f"(attendance_rate={existing.attendance_rate:.1f}%) — skipping."
        )
        return {"created": False, "attendance_rate": existing.attendance_rate}

    total_att = (
        db.query(func.count(AttendanceRecord.id))
        .filter(AttendanceRecord.student_id == student_id)
        .scalar()
        or 0
    )
    present_att = (
        db.query(func.count(AttendanceRecord.id))
        .filter(
            AttendanceRecord.student_id == student_id,
            AttendanceRecord.status == AttendanceStatus.PRESENT,
        )
        .scalar()
        or 0
    )
    attendance_rate = round(present_att / total_att * 100, 4) if total_att else 0.0
    log.info(
        f"[{student_id}] Computed attendance_rate from records: "
        f"{present_att}/{total_att} = {attendance_rate:.1f}%"
    )

    metric = StudentMetric(
        student_id=student_id,
        attendance_rate=attendance_rate,
        engagement_score=75.0,
        academic_performance_index=0.0,
        login_gap_days=0,
        failure_ratio=0.0,
        financial_risk_flag=False,
        commute_risk_score=1,
        semester_performance_trend=0.0,
        last_interaction=datetime.now(timezone.utc),
    )
    db.add(metric)
    db.flush()
    log.info(f"[{student_id}] StudentMetric created (attendance_rate={attendance_rate:.1f}%).")
    return {"created": True, "attendance_rate": attendance_rate}


def ensure_risk_score(db: Session, student_id: str) -> dict:
    """
    Run the existing ML risk computation pipeline for student_id if no
    RiskScore row exists.

    Strategy:
      1. Try compute_student_risk (requires app-startup singleton).
      2. If not initialized, try to load the active model directly via model_loader
         and then call compute_student_risk again.
      3. If model still unavailable, compute a rule-based score from
         the student's attendance_rate (already in student_metrics row).
         Uses the active model_version_id from the DB so the NOT NULL
         constraint is satisfied.
    """
    from app.models.analytics import RiskScore
    from app.models import ModelVersion

    existing = db.query(RiskScore).filter(RiskScore.student_id == student_id).first()
    if existing:
        log.info(
            f"[{student_id}] RiskScore already exists "
            f"(score={existing.risk_score:.1f}, level={existing.risk_level.value}) — skipping."
        )
        return {
            "created": False,
            "risk_score": existing.risk_score,
            "risk_level": existing.risk_level.value,
        }

    # Get the active model version from DB (required for NOT NULL constraint)
    active_model_version = (
        db.query(ModelVersion).filter(ModelVersion.is_active == True).first()
    )
    if not active_model_version:
        active_model_version = db.query(ModelVersion).order_by(ModelVersion.id.desc()).first()
    model_version_id = active_model_version.id if active_model_version else None

    # Attempt 1: use the running app's singleton pipeline
    try:
        from app.services.realtime_prediction import compute_student_risk
        result = compute_student_risk(student_id, db, save_to_db=True)
        db.flush()
        level_val = result["risk_level"].value if hasattr(result["risk_level"], "value") else str(result["risk_level"])
        log.info(
            f"[{student_id}] RiskScore created via ML pipeline (singleton): "
            f"score={result['risk_score']:.1f}, level={level_val}"
        )
        return {"created": True, "risk_score": result["risk_score"], "risk_level": level_val}

    except RuntimeError:
        pass  # Singleton not initialized — try direct model load

    # Attempt 2: load the active model directly and run inference
    try:
        from app.ml.model_loader import model_loader
        from app.services.realtime_prediction import (
            init_prediction_service, compute_student_risk
        )
        from app.services.risk_model import RiskModel
        from app.services.shap_explainer import SHAPExplainer

        if not model_loader.is_loaded and active_model_version:
            model_loader.load_model(active_model_version.model_path)

        if model_loader.is_loaded:
            risk_model = RiskModel(model_loader)
            shap_explainer = SHAPExplainer(risk_model)
            init_prediction_service(risk_model, shap_explainer, model_version_id)
            result = compute_student_risk(student_id, db, save_to_db=True)
            db.flush()
            level_val = result["risk_level"].value if hasattr(result["risk_level"], "value") else str(result["risk_level"])
            log.info(
                f"[{student_id}] RiskScore created via ML pipeline (direct load): "
                f"score={result['risk_score']:.1f}, level={level_val}"
            )
            return {"created": True, "risk_score": result["risk_score"], "risk_level": level_val}
    except Exception as e2:
        log.warning(f"[{student_id}] Direct ML model load failed: {e2}")

    # Attempt 3: rule-based score from attendance_rate (no fake values — derived from real data)
    log.warning(
        f"[{student_id}] ML pipeline not available. "
        "Computing rule-based risk score from attendance_rate."
    )
    from app.models.student import StudentMetric
    from app.models.enums import RiskLevel, RiskTrend

    metric = db.query(StudentMetric).filter(StudentMetric.student_id == student_id).first()
    attendance_rate = metric.attendance_rate if metric else 0.0

    # Rule: attendance < 60 → High Risk, < 75 → Moderate, < 85 → Stable, else Safe
    if attendance_rate < 60:
        risk_score, risk_level = 75.0, RiskLevel.HIGH
    elif attendance_rate < 75:
        risk_score, risk_level = 50.0, RiskLevel.MODERATE
    elif attendance_rate < 85:
        risk_score, risk_level = 30.0, RiskLevel.STABLE
    else:
        risk_score, risk_level = 15.0, RiskLevel.SAFE

    rs = RiskScore(
        student_id=student_id,
        risk_score=risk_score,
        risk_level=risk_level,
        risk_trend=RiskTrend.STABLE,
        risk_value=f"{int(risk_score)}%",
        shap_explanation={
            "top_factors": [
                {"feature": "attendance_rate", "impact": round((100 - attendance_rate) / 100, 4), "direction": "negative"}
            ]
        },
        model_version_id=model_version_id,
    )
    db.add(rs)
    db.flush()
    log.info(
        f"[{student_id}] Rule-based RiskScore inserted: "
        f"attendance={attendance_rate:.1f}% → score={risk_score}, level={risk_level.value}"
    )
    return {"created": True, "risk_score": risk_score, "risk_level": risk_level.value}


def initialize_student(db: Session, student_id: str) -> dict:
    """
    Run all three initialization steps for a single student_id.
    Idempotent — safe to call multiple times.
    """
    log.info(f"\n{'─' * 60}")
    log.info(f"Initializing relationships for: {student_id}")
    log.info(f"{'─' * 60}")

    assessment_result = repair_student_assessment_links(db, student_id)
    metric_result = ensure_student_metric(db, student_id)
    risk_result = ensure_risk_score(db, student_id)

    db.commit()
    log.info(f"[{student_id}] Committed. All three steps complete.\n")

    return {
        "student_id": student_id,
        "assessment_links": assessment_result,
        "student_metric": metric_result,
        "risk_score": risk_result,
    }


def initialize_all_students_missing_relationships(db: Session) -> list:
    """
    Find all enrolled students missing StudentAssessment rows and initialize them.
    """
    from app.models.academic import Enrollment, Assessment
    from app.models.records import StudentAssessment
    from sqlalchemy import distinct

    enrolled_student_ids = [
        row[0]
        for row in db.query(distinct(Enrollment.student_id)).all()
    ]

    results = []
    for student_id in enrolled_student_ids:
        enrolled_course_ids = [
            e.course_id
            for e in db.query(Enrollment).filter(Enrollment.student_id == student_id).all()
        ]
        total_assessments = (
            db.query(func.count(Assessment.id))
            .filter(Assessment.course_id.in_(enrolled_course_ids))
            .scalar()
            or 0
        )
        existing_links = (
            db.query(func.count(StudentAssessment.id))
            .filter(StudentAssessment.student_id == student_id)
            .scalar()
            or 0
        )

        if existing_links < total_assessments:
            log.info(
                f"[{student_id}] {total_assessments - existing_links} missing assessment links "
                "— running initialization."
            )
            result = initialize_student(db, student_id)
            results.append(result)

    return results


if __name__ == "__main__":
    from app.database.session import SessionLocal

    target_student_id = None
    if "--student-id" in sys.argv:
        idx = sys.argv.index("--student-id")
        if idx + 1 < len(sys.argv):
            target_student_id = sys.argv[idx + 1]

    db = SessionLocal()
    try:
        if target_student_id:
            log.info(f"Single-student mode: {target_student_id}")
            result = initialize_student(db, target_student_id)
            log.info(f"\nResult: {result}")
        else:
            log.info("All-students mode: scanning for missing relationships...")
            results = initialize_all_students_missing_relationships(db)
            log.info(f"\nComplete. Initialized {len(results)} students.")
    except Exception as e:
        db.rollback()
        log.error(f"Initialization failed: {e}")
        raise
    finally:
        db.close()
